R5   article blur words
TomaszDziedzicITA/redactlePL pull request #8
Opened 2022-10-05 07:53 UTC by T40N

Blur words working with mocked object.

2022-10-11 07:49 UTC, TomaszDziedzicITA requested changes

2022-10-11 10:59 UTC, T40N commented on src/pages/game/article/Article.tsx
> +`;
Done :)

2022-10-11 10:59 UTC, T40N commented on src/pages/game/article/Article.tsx
> +                return wordToBlur.word + ' ';
done :)

2022-10-11 10:59 UTC, T40N commented on src/pages/game/article/Article.tsx
> +    const blurWords = (wordsToBlurArray: WordToGuess[]) => {
I refactored it, but i wasn't sure if this is what you was thinking about.

2022-10-11 10:59 UTC, T40N commented on src/pages/game/article/Article.tsx
> +                    <BlurredText guessed={false}>{blurredWord}</BlurredText>{' '}
Yes, I forgot it again, it's last time I promise.
Since this text will not change it's order, I used index from map, to pass a key in to it.

2022-10-11 10:59 UTC, T40N commented on src/pages/game/article/Article.tsx
> +                    <BlurredText guessed={false}>{blurredWord}</BlurredText>{' '}
done :)

2022-10-11 10:59 UTC, T40N commented on src/pages/game/article/styled.tsx
> +  padding: 0;
done

2022-10-11 10:59 UTC, T40N commented on src/pages/game/article/styled.tsx
> +    guessed ? theme.palette.secondary.main : theme.palette.primary.main};
done :)

2022-10-11 11:22 UTC, TomaszDziedzicITA commented on src/pages/game/article/Article.tsx
> +                return wordToBlur.word + ' ';
I dont know why <span> was cut off from my comment. it should be "you should also wrap it in span". Please do so in Word component :)

2022-10-11 11:23 UTC, TomaszDziedzicITA requested changes
ok, almost there. Just one small adjustment to be made

2022-10-11 11:23 UTC, TomaszDziedzicITA commented on src/pages/game/article/Word.tsx
> +        return <>wordToBlur.word + ' '</>;
you can make it span, so we are consistent with the blurred word

2022-10-12 05:26 UTC, TomaszDziedzicITA approved these changes

2022-10-12 06:12 UTC, merged